# Generated by Django 6.0.6 on 2026-07-08 15:27

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='оригинальное имя')),
                ('storage_name', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='физическое имя')),
                ('relative_path', models.CharField(editable=False, max_length=255, unique=True, verbose_name='относительный путь')),
                ('size', models.BigIntegerField(verbose_name='размер в байтах')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='дата последнего скачивания')),
                ('public_token', models.CharField(default=storage.models.generate_public_token, editable=False, max_length=43, unique=True, verbose_name='публичный токен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['owner', 'uploaded_at'], name='storage_owner_uploaded_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size__gte', 0)), name='storage_file_size_non_negative')],
            },
        ),
    ]
